language: node_js
node_js:
  - '9.10.0'

cache: yarn

install:
  - npm install

before_script:
  - npm run test:coverage

script:
  - CI=false yarn build
  - npm run build-storybook

after_script:
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
  - bash scripts/gitbook.sh
