language: node_js
node_js:
  - '8.10.0'

cache: yarn

install:
  - yarn install

before_script:
  - yarn test:coverage

script:
  - yarn build
  - yarn build-storybook

after_script:
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
  - bash scripts/gitbook.sh
